# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\"\x1c\n\tProcessed\x12\x0f\n\x07success\x18\x01 \x01(\x08\"4\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0f\n\x07\x63olumns\x18\x03 \x01(\x05\"H\n\nPointCloud\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0f\n\x07\x63olumns\x18\x03 \x01(\x05\x12\r\n\x05\x64\x65pth\x18\x04 \x01(\x05\x32`\n\x0eImageProcessor\x12!\n\tSendImage\x12\x06.Image\x1a\n.Processed\"\x00\x12+\n\x0eSendPointCloud\x12\x0b.PointCloud\x1a\n.Processed\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSED._serialized_start=15
  _PROCESSED._serialized_end=43
  _IMAGE._serialized_start=45
  _IMAGE._serialized_end=97
  _POINTCLOUD._serialized_start=99
  _POINTCLOUD._serialized_end=171
  _IMAGEPROCESSOR._serialized_start=173
  _IMAGEPROCESSOR._serialized_end=269
# @@protoc_insertion_point(module_scope)
